language: he
lang_direction: rtl
landing_page:
  welcome_message:
    text: 'ברוכים הבאים למסיבה שלי!'
  name_form:
    text: 'מה שמך הפרטי ומהי סיסמת המסיבה?'
    name_placeholder_text: השם שלך כאן
    password_placeholder_text: סיסמא כאן
    submit_button_text: שלח
navbar:
  title:
    text: יום הולדת של יהודה 🥳
text_chat:
  submit_button_text: שלח
  placeholder_text: 'ההודעה שלך עוברת לכאן'

